services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - backend
    restart: always
    
networks:
  backend:

volumes:
  mongodb_data: